KCite Test
==========
:blogpost-status: published
:blogpost-categories: kcite

A big pass through block.


DOI Citation: In Google we trust.
pass:[[cite\]10.3998/3336451.0009.101[/cite\]]

PubMed Citation: Proteomi analysis of the left ventricle
New in PubMed pass:[[cite source='pubmed'\]21237295[/cite\]].

Integrated dataset. 
This is a DOI in the middle of some text
pass:[[cite\]10.2390/biecoll-jib-2010-116[/cite\]]. It should be
interpreted too.


This is a DOI that is a duplicate of another DOI: In google we trust. 
pass:[[cite\]10.3998/3336451.0009.101[/cite\]]. We need to make sure these are
handled too.

This DOI matches a citeproc example. Key Process Conditions for Production
pass:[[cite\]10.1128/AEM.02396-09[/cite\]]. 

This one is a brand new paper, to test speed of resolution (published 7th Jan
2011): Proteome-wide Identification of WRN-Interacting Proteins in Untreated
and Nuclease-Treated Samples pass:[[cite\]10.1021/pr100990s[/cite\]].

This is a test for the new style shortcode. In google we trust again.
pass:[[cite source='doi'\]10.3998/3336451.0009.101[/cite\]]. 

And for Pubmed pass:[[cite source='pubmed'\]17237047[/cite\]]. And using the
default (and a duplicate) pass:[[cite\]10.3998/3336451.0009.101[/cite\]].

Test with cito attribute -- currently ignored.
pass:[[cite rel="cito:brilliant"\]10.1371/journal.pone.0012258[/cite\]]

