Really big kcite Test
=====================
:blogpost-status: published
:blogpost-categories: kcite


This is a big list of hopefully, mostly unique DOIs. This should test out the
transients API. 

pass:[[cite\]10.1093/nar/gkl799[/cite\]]
pass:[[cite\]10.1186/1471-2105-8-284[/cite\]]
pass:[[cite\]10.1186/1471-2105-8-57[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btn194[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btm229[/cite\]]
pass:[[cite\]10.1016/j.websem.2005.09.003[/cite\]]
pass:[[cite\]10.1093/bioinformatics/bth088[/cite\]]
pass:[[cite\]10.1371/journal.pcbi.0010034[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btl266[/cite\]]
pass:[[cite\]10.1371/journal.pcbi.0010076[/cite\]]
pass:[[cite\]10.1136/jmg.2007.048876[/cite\]]
pass:[[cite\]10.1007/s00439-005-0123-8[/cite\]]
pass:[[cite\]10.1016/j.tig.2006.09.004[/cite\]]
pass:[[cite\]10.1002/humu.21113[/cite\]]
pass:[[cite\]10.1093/nar/gkm1037[/cite\]]
pass:[[cite\]10.1186/1471-2105-9-78[/cite\]]
pass:[[cite\]10.1016/j.jbi.2005.08.005[/cite\]]
pass:[[cite\]10.1093/bioinformatics/bth921[/cite\]]
pass:[[cite\]10.1038/nature02236[/cite\]]
pass:[[cite\]10.1093/bib/bbl014[/cite\]]
pass:[[cite\]10.1038/nrm1013[/cite\]]
pass:[[cite\]10.1093/nar/gkl841[/cite\]]
pass:[[cite\]10.1186/gb-2010-11-1-r2[/cite\]]
pass:[[cite\]10.1186/1471-2105-9-353[/cite\]]
pass:[[cite\]10.1016/j.ajhg.2007.09.018[/cite\]]
pass:[[cite\]10.1111/j.1474-9726.2009.00492.x[/cite\]]
pass:[[cite\]10.1093/bioinformatics/bth040[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btm319[/cite\]]
pass:[[cite\]10.1016/j.jbi.2003.11.007[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btn158[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btg277[/cite\]]
pass:[[cite\]10.1093/nar/gkh116[/cite\]]
pass:[[cite\]10.1038/nbt1346[/cite\]]
pass:[[cite\]10.1186/gb-2005-6-5-r46[/cite\]]
pass:[[cite\]10.1038/417119a[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btm195[/cite\]]
pass:[[cite\]10.1101/gr.180801[/cite\]]
pass:[[cite\]10.1110/ps.062184006[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btl005[/cite\]]
pass:[[cite\]10.1093/bioinformatics/bth938[/cite\]]
pass:[[cite\]10.1093/bioinformatics/btl208[/cite\]]
pass:[[cite\]10.1101/gr.1774904[/cite\]]
pass:[[cite\]10.1186/1471-2105-6-168[/cite\]]


Followed by a really large set of PMIDs

pass:[[cite source="pubmed"\]20958790[/cite\]]
pass:[[cite source="pubmed"\]20838431[/cite\]]
pass:[[cite source="pubmed"\]20626927[/cite\]]
pass:[[cite source="pubmed"\]20626924[/cite\]]
pass:[[cite source="pubmed"\]20626923[/cite\]]
pass:[[cite source="pubmed"\]20626920[/cite\]]
pass:[[cite source="pubmed"\]20406369[/cite\]]
pass:[[cite source="pubmed"\]20375448[/cite\]]
pass:[[cite source="pubmed"\]20056575[/cite\]]
pass:[[cite source="pubmed"\]20032223[/cite\]]
pass:[[cite source="pubmed"\]19878003[/cite\]]
pass:[[cite source="pubmed"\]19765219[/cite\]]
pass:[[cite source="pubmed"\]19674279[/cite\]]
pass:[[cite source="pubmed"\]19649320[/cite\]]
pass:[[cite source="pubmed"\]19441879[/cite\]]
pass:[[cite source="pubmed"\]19037886[/cite\]]
pass:[[cite source="pubmed"\]18688244[/cite\]]
pass:[[cite source="pubmed"\]18629196[/cite\]]
pass:[[cite source="pubmed"\]18629147[/cite\]]
pass:[[cite source="pubmed"\]18629114[/cite\]]
pass:[[cite source="pubmed"\]18629028[/cite\]]
pass:[[cite source="pubmed"\]18464787[/cite\]]
pass:[[cite source="pubmed"\]18281259[/cite\]]
pass:[[cite source="pubmed"\]18048194[/cite\]]
pass:[[cite source="pubmed"\]18018735[/cite\]]
pass:[[cite source="pubmed"\]17918543[/cite\]]
pass:[[cite source="pubmed"\]17483389[/cite\]]
pass:[[cite source="pubmed"\]17442663[/cite\]]
pass:[[cite source="pubmed"\]17381134[/cite\]]
pass:[[cite source="pubmed"\]17311682[/cite\]]
pass:[[cite source="pubmed"\]16926038[/cite\]]
pass:[[cite source="pubmed"\]16921489[/cite\]]
pass:[[cite source="pubmed"\]16873517[/cite\]]
pass:[[cite source="pubmed"\]16772270[/cite\]]
pass:[[cite source="pubmed"\]16758510[/cite\]]
pass:[[cite source="pubmed"\]16758004[/cite\]]
pass:[[cite source="pubmed"\]16700814[/cite\]]
pass:[[cite source="pubmed"\]16553156[/cite\]]
pass:[[cite source="pubmed"\]16412133[/cite\]]
pass:[[cite source="pubmed"\]20020997[/cite\]]
pass:[[cite source="pubmed"\]15982685[/cite\]]
pass:[[cite source="pubmed"\]15976123[/cite\]]
pass:[[cite source="pubmed"\]15869155[/cite\]]
pass:[[cite source="pubmed"\]15759616[/cite\]]
pass:[[cite source="pubmed"\]15498974[/cite\]]
pass:[[cite source="pubmed"\]15460068[/cite\]]
pass:[[cite source="pubmed"\]15262813[/cite\]]
pass:[[cite source="pubmed"\]15093283[/cite\]]
pass:[[cite source="pubmed"\]15074629[/cite\]]
pass:[[cite source="pubmed"\]15033589[/cite\]]



And a final set of pubmed IDs


pass:[[cite source="pubmed"\]21355555[/cite\]]
pass:[[cite source="pubmed"\]21325286[/cite\]]
pass:[[cite source="pubmed"\]21304727[/cite\]]
pass:[[cite source="pubmed"\]21291516[/cite\]]
pass:[[cite source="pubmed"\]21272235[/cite\]]
pass:[[cite source="pubmed"\]21231389[/cite\]]
pass:[[cite source="pubmed"\]21208951[/cite\]]
pass:[[cite source="pubmed"\]21207283[/cite\]]
pass:[[cite source="pubmed"\]21204936[/cite\]]
pass:[[cite source="pubmed"\]21181124[/cite\]]
pass:[[cite source="pubmed"\]21173247[/cite\]]
pass:[[cite source="pubmed"\]21123443[/cite\]]
pass:[[cite source="pubmed"\]21123128[/cite\]]
pass:[[cite source="pubmed"\]21115275[/cite\]]
pass:[[cite source="pubmed"\]21115031[/cite\]]
pass:[[cite source="pubmed"\]21113017[/cite\]]
pass:[[cite source="pubmed"\]21109193[/cite\]]
pass:[[cite source="pubmed"\]21097933[/cite\]]
pass:[[cite source="pubmed"\]21077952[/cite\]]
pass:[[cite source="pubmed"\]21076331[/cite\]]
pass:[[cite source="pubmed"\]21076070[/cite\]]
pass:[[cite source="pubmed"\]21072206[/cite\]]
pass:[[cite source="pubmed"\]21067627[/cite\]]
pass:[[cite source="pubmed"\]21029416[/cite\]]
pass:[[cite source="pubmed"\]20962033[/cite\]]
pass:[[cite source="pubmed"\]20929726[/cite\]]
pass:[[cite source="pubmed"\]20921216[/cite\]]
pass:[[cite source="pubmed"\]20867768[/cite\]]
pass:[[cite source="pubmed"\]20863482[/cite\]]
pass:[[cite source="pubmed"\]20838431[/cite\]]
pass:[[cite source="pubmed"\]20827368[/cite\]]
pass:[[cite source="pubmed"\]20826331[/cite\]]
pass:[[cite source="pubmed"\]20802497[/cite\]]
pass:[[cite source="pubmed"\]20728092[/cite\]]
pass:[[cite source="pubmed"\]20702086[/cite\]]
pass:[[cite source="pubmed"\]20700723[/cite\]]
pass:[[cite source="pubmed"\]20680434[/cite\]]
pass:[[cite source="pubmed"\]20672697[/cite\]]
pass:[[cite source="pubmed"\]20669948[/cite\]]
pass:[[cite source="pubmed"\]20665643[/cite\]]
pass:[[cite source="pubmed"\]20665265[/cite\]]
pass:[[cite source="pubmed"\]20621498[/cite\]]
pass:[[cite source="pubmed"\]20620995[/cite\]]
pass:[[cite source="pubmed"\]20603344[/cite\]]
pass:[[cite source="pubmed"\]20562050[/cite\]]
pass:[[cite source="pubmed"\]20546611[/cite\]]
pass:[[cite source="pubmed"\]20544957[/cite\]]
pass:[[cite source="pubmed"\]20529510[/cite\]]
pass:[[cite source="pubmed"\]20493882[/cite\]]


=== Problematic Cases

This DOI don't work, probably because it's wrong.
pass:[[cite\]10.3233/AO-2010-0076[/cite\]]



This pubmed ID doesn't work because it returns a title with 
a double quote in it which breaks my JSON. Hopefully, this problem will go
away when I use something more sane. 
// pass:[[cite source="pubmed"\]21304728[/cite\]]

